pipeline {
    agent any

    stages {
        stage ('build') {
            steps {
                sh('echo "Building..."')
            }
        }

        stage ('embedde') {
            steps {
                script {
                    echo "embedde..."
                }
            }
        }
    }
}