environment {
    DISABLE_AUTH = 'true'
}

properties([
    buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '20')),
    parameters([
        choice(name: "environment", choices: ['dev', 'test', 'staging', 'prod'], description: "部署环境")
    ]),
])

stage('Checkout') {
    checkout scm
}

stage('Build and Test') {
    pipeBuild.mavenBuildAndTest()
}

stage('Build Docker Image') {
    pipeBuild.buildDockerImage("docker build -t spring-start-monitor:latest .")
}

stage('Push to ECR') {
    pipeBuild.pushDockerImageToECR("")
}

stage('Deploy to EKS') {
    pipeBuild.deploy("")
}